Repository yeogiya/yeogiya-frontend, pull requests merged in 2023-12, with the labels that each got.

#66 feat: ✨ 지도 페이지 API(PP-159)
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/images/LocationIcon.tsx
  src/assets/images/MapSearchIcon.tsx
  src/assets/images/svg/marker.svg
  src/assets/index.ts
  src/components/@common/Map.tsx
  src/components/MapHeader.tsx
  src/features/hooks/useAppDispatch.ts
  src/features/hooks/useMap.ts
  src/index.tsx
  src/pages/diary/map/MapPage.tsx
  src/pages/home/components/ContentDiary.tsx
  src/pages/home/components/ContentHeader.tsx
  src/store/diarySlice.ts
  src/store/store.ts
  src/types/global.d.ts
  src/types/map.ts
  tsconfig.json
Labels: feat ✨

#67 style: 💄 위치 검색 페이지 UI - 입력(PP-165)
  src/App.tsx
  src/assets/images/BgCloseIcon.tsx
  src/assets/images/LeftArrowIcon.tsx
  src/assets/index.ts
  src/components/@common/Header.tsx
  src/components/@common/HeadingText.tsx
  src/components/@common/Navbar.tsx
  src/components/IconButton.tsx
  src/components/MapHeader.tsx
  src/pages/diary/map/MapPage.tsx
  src/pages/diary/map/components/Map.tsx
  src/pages/diary/map/components/MapNavbar.tsx
  src/pages/diary/map/search/MapSearchPage.tsx
  src/pages/diary/map/search/components/LocationSearch.tsx
  src/pages/diary/map/search/components/LocationSearchNavbar.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#69 feat: ✨ 로그인 페이지 - validation(PP-19)
  src/apis/apiUrl.ts
  src/apis/user.ts
  src/components/@common/Layout.tsx
  src/components/@common/LinkText.tsx
  src/features/hooks/useLoginForm.ts
  src/mocks/handlers.ts
  src/mocks/mocksUrl.ts
  src/pages/join/JoinPage.tsx
  src/pages/join/components/InputConfirmPassword.tsx
  src/pages/join/components/InputEmail.tsx
  src/pages/join/components/InputId.tsx
  src/pages/join/components/InputNickname.tsx
  src/pages/join/components/InputPassword.tsx
  src/pages/login/LoginPage.tsx
Labels: feat ✨, refac ♻️

#73 style: 💄 마이 페이지 UI(PP-175)
  src/assets/images/ProfileIcon.tsx
  src/components/@common/Layout.tsx
  src/features/hooks/useMyForm.ts
  src/pages/join/components/InputNickname.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/components/InputProfile.tsx
  src/styles/theme.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨, style 💄

#78 feat: ✨ 로그인 페이지 - 카카오 로그인 API(PP-178)
  index.html
  src/apis/user.ts
  src/components/@common/Button.tsx
  src/components/@common/DefaultButton.tsx
  src/components/@common/Layout.tsx
  src/components/@common/Title.tsx
  src/components/SubmitButton.tsx
  src/features/hooks/useJoinForm.ts
  src/features/hooks/useMyForm.ts
  src/pages/find/id/FindIdPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/types/global.d.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨

#82 chore: 👷‍♂️ 배포 설정(PP-180)
  .github/workflows/deploy.yml
  build.sh
  src/pages/diary/map/search/components/LocationSearch.tsx
  src/pages/diary/map/search/components/LocationSearchNavbar.tsx
  src/styles/GlobalStyle.tsx
  vercel.json
Labels: chore 🛠️

#85 fix: 🐛 자동배포 에러(PP-186)
  .github/workflows/deploy.yml
  package.json
Labels: fix 🐛

#81 feat: ✨ 비밀번호 찾기 페이지 API(PP-55)
  src/apis/apiUrl.ts
  src/apis/user.ts
  src/components/@common/Modal.tsx
  src/components/InputEmail.tsx
  src/components/InputId.tsx
  src/components/InputPassword.tsx
  src/features/hooks/useFindPwForm.ts
  src/pages/find/pw/FindPwPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/my/password/MyPwPage.tsx
  src/pages/my/password/UpdateMyPwPage.tsx
  src/pages/reset/ResetPwPage.tsx
Labels: feat ✨, refac ♻️

#87 fix: 🐛 fix bug(PP-156)
  public/images/checkbox.svg
  public/images/uncheckbox.svg
  src/apis/user.ts
  src/assets/images/svg/whitePlusIcon.svg
  src/components/@common/HeadingText.tsx
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/create/components/DatePicker.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/find/id/FindIdPage.tsx
  src/pages/home/LandingPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/pages/my/withdrawal/WithdrawalPage.tsx
  src/styles/GlobalStyle.tsx
  src/utils/Router.tsx
  src/utils/menus.ts
  src/utils/routes.ts
Labels: fix 🐛

#89 feat: ✨ 지도 페이지(PP-187)
  .github/workflows/deploy.yml
  index.html
  src/features/hooks/useMap.ts
  src/features/hooks/usePageNavigation.ts
  src/pages/diary/map/MapPage.tsx
  src/pages/diary/map/components/MapNavbar.tsx
  src/pages/diary/map/search/components/LocationSearchNavbar.tsx
  src/store/diarySlice.ts
  src/utils/Router.tsx
Labels: feat ✨

#90 feat: ⚡️ 회원정보 API 연동(PP-188)
  src/apis/apiUrl.ts
  src/apis/queryKey.ts
  src/apis/user.ts
  src/components/@common/Navbar.tsx
  src/features/hooks/useJoinForm.ts
  src/mocks/handlers.ts
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
Labels: feat ✨

#92 chore: 🛠️ router 설정(PP-193)
  .github/workflows/deploy.yml
  src/App.tsx
  src/pages/search/components/PlaceSearchNavbar.tsx
  src/pages/search/list/SearchListPage.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: chore 🛠️

#99 style: 💄 로그인 유저 navbar UI(PP-194)
  public/images/profile.svg
  src/components/@common/Menu.tsx
  src/components/@common/Navbar.tsx
  src/utils/menus.ts
Labels: style 💄

#100 style: 💄 식당 더보기 상세 페이지 UI - navbar
  src/App.tsx
  src/assets/images/png/placeImage.png
  src/assets/images/svg/profile.svg
  src/assets/index.ts
  src/components/@common/Navbar.tsx
  src/features/hooks/useMap.ts
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/home/components/ContentPlace.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/list/ResultListPage.tsx
  src/pages/search/list/SearchListPage.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#98 fix: 🐛 회원정보조회, 공간일기작성 error & UI
  index.html
  public/images/favicon.png
  src/apis/apiUrl.ts
  src/apis/diary.ts
  src/apis/httpClient.ts
  src/apis/user.ts
  src/components/@common/Menu.tsx
  src/components/@common/Navbar.tsx
  src/constants/category.ts
  src/constants/menus.ts
  src/constants/queryKey.ts
  src/constants/token.ts
  src/constants/url.ts
  src/contexts/TokenProvider.tsx
  src/features/hooks/queries/useCheckEmail.ts
  src/features/hooks/queries/useJoin.ts
  src/features/hooks/queries/useLogin.ts
  src/features/hooks/queries/useUserInfo.ts
  src/features/hooks/useFindPwForm.ts
  src/features/hooks/useJoinForm.ts
  src/features/hooks/useMyForm.ts
  src/features/hooks/useToken.ts
  src/index.tsx
  src/pages/diary/create/components/InputTag.tsx
  src/pages/diary/create/components/UploadImage.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/find/id/FindIdPage.tsx
  src/pages/find/pw/FindPwPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/utils/Router.tsx
Labels: fix 🐛

#101 style: 💄 회원 탈퇴 안내, 완료 페이지 UI(PP-177)
  index.html
  src/assets/images/png/checkImage.png
  src/assets/index.ts
  src/components/@common/ContentLayout.tsx
  src/components/@common/HeadingText.tsx
  src/components/@common/Menu.tsx
  src/constants/withdrawal.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/find/id/FindIdPage.tsx
  src/pages/find/pw/FindPwPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/password/MyPwPage.tsx
  src/pages/my/password/UpdateMyPwPage.tsx
  src/pages/my/withdrawal/ConfirmWithdrawalPage.tsx
  src/pages/my/withdrawal/WithdrawalPage.tsx
  src/pages/reset/ResetPwPage.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#102 style: 💄 식당 더보기 상세 페이지 UI - Carousel
  src/assets/images/ArrowLeftIcon.tsx
  src/assets/index.ts
  src/components/@common/Image.tsx
  src/components/@common/Menu.tsx
  src/constants/menus.ts
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/components/Carousel.tsx
  src/pages/result/detail/components/ImageSection.tsx
Labels: style 💄

#104 feat: ⚡️ reissue token & protect route 적용(PP-204)
  src/App.tsx
  src/apis/auth.ts
  src/components/@common/LinkText.tsx
  src/components/@common/Menu.tsx
  src/constants/url.ts
  src/features/hooks/queries/useReissueToken.ts
  src/pages/my/withdrawal/WithdrawalPage.tsx
  src/utils/ProtectRouter.tsx
  src/utils/Router.tsx
Labels: feat ✨

#107 style: 💄 식당 더보기 상세 페이지 UI(PP-206)
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  public/images/profile.svg
  src/assets/images/ShareIcon.tsx
  src/assets/images/StarIcon.tsx
  src/assets/images/png/white.png
  src/assets/index.ts
  src/components/@common/Menu.tsx
  src/constants/diary.ts
  src/constants/menus.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/map/components/Map.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/components/Carousel.tsx
  src/pages/result/detail/components/DiaryReview.tsx
  src/pages/result/detail/components/ImageSection.tsx
  src/pages/result/detail/components/RestaurantTitle.tsx
  src/pages/result/detail/components/ResultDetailContent.tsx
  src/pages/result/detail/components/ResultDetailNav.tsx
  src/pages/result/detail/components/ResultDetailReview.tsx
Labels: style 💄

#111 feat: ⚡️ 공간일기 목록 페이지 API(PP-167)
  src/constants/diary.ts
  src/constants/queryKey.ts
  src/features/hooks/queries/useDiaryList.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/create/components/TextArea.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/diary/map/MapPage.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/components/ImageSection.tsx
  src/pages/result/detail/components/ResultDetailReview.tsx
  src/store/diarySlice.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨

#116 fix: 🐛 mixed content bug fix(PP-210)
  index.html
Labels: fix 🐛

#112 style: 💄✨ 장소 검색 리스트 페이지 UI, API
  .github/workflows/deploy.yml
  src/apis/search.ts
  src/assets/images/GoogleRatingIcon.tsx
  src/assets/images/RightArrowIcon.tsx
  src/assets/index.ts
  src/components/@common/ScrollToTop.tsx
  src/components/InfoItem.style.ts
  src/components/InfoItem.tsx
  src/constants/queryKey.ts
  src/constants/url.ts
  src/features/hooks/queries/useLocationSearch.ts
  src/pages/diary/create/components/InputTag.tsx
  src/pages/diary/create/components/Rating.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/components/DiaryReview.tsx
  src/pages/result/detail/components/ResultDetailContent.tsx
  src/pages/result/detail/components/ResultDetailReview.tsx
  src/pages/result/list/ResultListPage.tsx
  src/pages/result/list/components/ResultTitle.tsx
  src/pages/search/SearchPage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨, style 💄

#118 fix: 🐛 bug(PP-211)
  index.html
  src/constants/queryKey.ts
  src/features/hooks/queries/useLocationSearch.ts
Labels: fix 🐛

#124 feat: ✨ 장소 검색 Navbar
  .github/workflows/deploy.yml
  src/components/@common/Navbar.tsx
  src/components/InfoItem.style.ts
  src/features/hooks/usePlaceSearch.ts
  src/pages/search/SearchPage.tsx
Labels: feat ✨, style 💄

#126 feat: ⚡️ 탈퇴 API 연동(PP-216)
  src/apis/user.ts
  src/constants/url.ts
  src/constants/withdrawal.ts
  src/features/hooks/queries/useWithdraw.ts
  src/pages/my/withdrawal/WithdrawalPage.tsx
  src/types/users.ts
Labels: feat ✨

#127 feat: ✨🐛🤡 로그인 페이지 - 카카오 간편로그인
  src/App.tsx
  src/apis/search.ts
  src/constants/diary.ts
  src/features/hooks/queries/useRestaurant.ts
  src/mocks/handlers.ts
  src/mocks/mocksUrl.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/components/Carousel.tsx
  src/pages/result/detail/components/DiaryReview.tsx
  src/pages/result/detail/components/RestaurantTitle.tsx
  src/pages/result/detail/components/ResultDetailNav.tsx
  src/store/store.ts
  src/store/userSlice.ts
Labels: fix 🐛, chore 🛠️, feat ✨

#128 feat: ✨ 구글 로그인 API 연동(PP-217)
  package.json
  pnpm-lock.yaml
  src/apis/auth.ts
  src/apis/httpClient.ts
  src/components/@common/Menu.tsx
  src/constants/url.ts
  src/features/hooks/queries/useLogin.ts
  src/index.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/store/store.ts
  src/store/userSlice.ts
  src/types/users.ts
Labels: feat ✨, refac ♻️

#130 refac: ♻️ 로그인 페이지 - 구글 로그인 API refactoring(PP-218)
  src/apis/auth.ts
  src/constants/url.ts
  src/pages/login/LoginPage.tsx
Labels: refac ♻️

#131 feat: ✨ 로그인 페이지 - 카카오 간편로그인(PP-169)
  src/apis/auth.ts
  src/apis/httpClient.ts
  src/constants/url.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/pages/login/components/SNSLogin.tsx
  src/store/store.ts
  src/store/tokenSlice.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨, refac ♻️

#132 refac: ♻️ 로그인 페이지 - 구글, 카카오 로그인 API(PP-218)
  index.html
  package.json
  src/apis/auth.ts
  src/components/@common/Menu.tsx
  src/constants/url.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/components/KakaoLogin.tsx
  src/types/users.ts
  src/utils/Router.tsx
Labels: refac ♻️

#134 feat: ✨ 로그인 유저 비밀번호 재설정 페이지 API(PP-62)
  src/apis/user.ts
  src/components/InputPassword.tsx
  src/components/SubmitButton.tsx
  src/components/ValidateMessage.tsx
  src/constants/url.ts
  src/features/hooks/queries/useAuthResetPw.ts
  src/features/hooks/queries/useCurrentPw.ts
  src/features/hooks/queries/useResetPw.ts
  src/features/hooks/useUpdateMyPw.ts
  src/pages/my/password/MyPwPage.tsx
  src/pages/my/password/UpdateMyPwPage.tsx
  tsconfig.json
  vite.config.ts
Labels: feat ✨

#135 chore: ⚒️ settings(PP-220)
  index.html
  package.json
  src/pages/login/LoginPage.tsx
  src/pages/login/components/SNSLogin.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
  tsconfig.json
  vercel.json
  vite.config.ts
Labels: chore 🛠️

#108 feat: ⚡️ 마이페이지 - 닉네임, 프로필 이미지 수정 API(PP-207)
  index.html
  public/images/favicon.ico
  public/images/favicon.png
  src/apis/httpClient.ts
  src/apis/user.ts
  src/components/InputNickname.tsx
  src/constants/queryKey.ts
  src/features/hooks/queries/useChangeNickname.ts
  src/features/hooks/queries/useChangeUserInfo.ts
  src/features/hooks/useMyForm.ts
  src/pages/login/LoginPage.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/components/InputProfile.tsx
Labels: feat ✨

#137 feat: ✨ 간편로그인 - token(PP-221)
  src/components/@common/Menu.tsx
  src/constants/menus.ts
  src/pages/404/NotFoundPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/error/ErrorPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/SNSLogin.tsx
  src/store/diarySlice.ts
  src/store/userSlice.ts
  src/utils/Router.tsx
  vite.config.ts
Labels: feat ✨
