Repository yeogiya/yeogiya-frontend, pull requests merged in 2023-09, with the labels that each got.

#7 style: 💄 로그인 페이지 UI
  src/assets/GoogleLogo.tsx
  src/assets/KakaoLogo.tsx
  src/components/@common/Button.tsx
  src/components/@common/HeadingText.tsx
  src/components/@common/InputUser.tsx
  src/components/@common/Layout.tsx
  src/components/@common/LinkText.tsx
  src/pages/LoginPage.tsx
  src/styles/globalStyle.ts
Labels: style 💄

#10 style: 💄 Navbar UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/SearchIcon.tsx
  src/assets/YeogiyaLogo.tsx
  src/components/@common/LinkText.tsx
  src/components/@common/Menu.tsx
  src/components/@common/Navbar.tsx
  src/components/Search.tsx
  src/styles/theme.ts
  src/utils/Router.tsx
  src/utils/menu.ts
  src/utils/routes.ts
Labels: style 💄

#11 style: 💄 회원가입 페이지 UI
  src/assets/ConcealIcon.tsx
  src/components/@common/Button.tsx
  src/components/@common/InputUser.tsx
  src/components/@common/Layout.tsx
  src/components/@common/Title.tsx
  src/components/CheckButton.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/utils/Router.tsx
Labels: style 💄

#15 chore: 📦 프로젝트 세팅(PP-98)
  package-lock.json
  package.json
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: chore 🛠️

#16 feat: ⚡️ react-hook-form 적용(PP-92)
  package-lock.json
  package.json
  src/assets/ConcealIcon.tsx
  src/components/@common/InputUser.tsx
  src/components/CheckButton.tsx
  src/pages/JoinPage.tsx
Labels: feat ✨

#18 fix: 🐛 navbar - responsive(PP-103)
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/@common/Button.tsx
  src/components/@common/LinkText.tsx
  src/components/@common/Menu.tsx
  src/components/@common/Navbar.tsx
  src/components/Search.tsx
  src/components/SearchBar.tsx
  src/stories/components/@common/Button.stories.tsx
  src/stories/components/SearchBar.stories.tsx
  src/utils/menu.ts
  src/utils/menus.ts
  src/utils/routes.ts
  tsconfig.json
Labels: fix 🐛

#30 style: 💄 아이디 찾기 페이지 UI(PP-47)
  src/components/@common/InputUser.tsx
  src/components/BasicButton.tsx
  src/pages/FindIdPage.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨, style 💄

#32 style: 💄 storybook & refactoring(PP-113)
  src/assets/ConcealIcon.tsx
  src/components/@common/Button.tsx
  src/components/@common/DefaultButton.tsx
  src/components/@common/InputUser.tsx
  src/components/BasicButton.tsx
  src/components/CheckButton.tsx
  src/components/IconButton.tsx
  src/components/SubmitButton.tsx
  src/pages/FindIdPage.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/stories/components/@common/Button.stories.tsx
  src/stories/components/@common/CheckButton.stories.tsx
  src/stories/components/@common/IconButton.stories.tsx
  src/stories/components/@common/SubmitButton.stories.tsx
  src/styles/theme.ts
Labels: style 💄

#34 style: 💄 storybook(input) & refactoring(PP-115)
  package-lock.json
  package.json
  src/components/@common/InputUser.tsx
  src/stories/components/@common/CheckButton.stories.tsx
  src/stories/components/@common/Input.stories.tsx
  src/stories/components/SearchBar.stories.tsx
Labels: chore 🛠️, style 💄, refac ♻️

#35 style: 💄 storybook(validateMessage) & 비밀번호 재설정 페이지 UI(PP-61)
  src/components/ValidateMessage.tsx
  src/pages/JoinPage.tsx
  src/pages/ResetPwPage.tsx
  src/stories/components/@common/Button.stories.tsx
  src/stories/components/ValidationMessage.stories.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#37 style: 💄 modal 공통 컴포넌트 생성(PP-58)
  src/components/@common/Modal.tsx
  src/features/hooks/useModal.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#38 style: 💄 비밀번호 찾기 페이지 UI(PP-56)
  src/components/@common/DefaultButton.tsx
  src/components/SubmitButton.tsx
  src/pages/FindPwPage.tsx
Labels: style 💄
