Repository yeogiya/yeogiya-frontend, pull requests merged in 2024-01, with the labels that each got.

#139 refac: ♻️ nav bar(PP-222)
  package.json
  pnpm-lock.yaml
  src/apis/diary.ts
  src/components/@common/Menu.tsx
  src/components/InputPassword.tsx
  src/constants/userInfo.ts
  src/features/hooks/queries/useDiaryList.ts
  src/features/hooks/queries/useLogin.ts
  src/features/hooks/useInfo.ts
  src/index.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/login/components/SNSLogin.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/password/MyPwPage.tsx
  src/store/store.ts
  src/store/tokenSlice.ts
  src/store/userSlice.ts
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨, refac ♻️

#141 fix: 🐛 bug 수정(PP-226)
  src/features/hooks/useMap.ts
  src/features/hooks/useMyForm.ts
  src/pages/my/MyPage.tsx
  src/pages/my/password/UpdateMyPwPage.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
Labels: fix 🐛

#143 style: 💄 공간일기 상세 페이지 - UI(PP-227)
  src/assets/images/StarIcon.tsx
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/detail/DiaryDetailPage.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: style 💄

#147 feat: ⚡️ 공간일기 삭제 API 연동(PP-232)
  src/apis/diary.ts
  src/features/hooks/queries/useDeleteDiary.ts
  src/pages/diary/detail/DiaryDetailPage.tsx
Labels: feat ✨

#150 feat: ✨💄 식당 더보기 페이지 - API, 기타 기능(PP-213)
  src/apis/search.ts
  src/assets/images/svg/searchDefaultImg.svg
  src/assets/index.ts
  src/components/@common/Navbar.tsx
  src/components/InfoItem.style.ts
  src/components/InfoItem.tsx
  src/constants/menus.ts
  src/constants/queryKey.ts
  src/constants/search.ts
  src/constants/url.ts
  src/features/hooks/queries/usePlaceSearch.ts
  src/features/hooks/queries/useRestaurant.ts
  src/features/hooks/queries/useSearchDetail.ts
  src/features/hooks/useSearch.ts
  src/pages/diary/map/components/Map.tsx
  src/pages/result/detail/RestaurantDetailPage.tsx
  src/pages/result/detail/SearchDetailPage.tsx
  src/pages/result/detail/components/Carousel.tsx
  src/pages/result/detail/components/ImageSection.tsx
  src/pages/result/detail/components/RestaurantTitle.tsx
  src/pages/result/detail/components/ResultDetailContent.tsx
  src/pages/result/detail/components/ResultDetailNav.tsx
  src/pages/result/place/PlaceListPage.tsx
  src/pages/result/place/components/PlaceSearchTitle.tsx
  src/pages/search/SearchPage.tsx
  src/store/placeSlice.ts
  src/store/store.ts
  src/utils/Router.tsx
Labels: feat ✨, style 💄

#152 feat: ✨ 공간일기 작성 페이지 API(PP-130)
  src/apis/diary.ts
  src/constants/category.ts
  src/constants/token.ts
  src/constants/userInfo.ts
  src/constants/withdrawal.ts
  src/features/hooks/queries/useCreateDiary.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/create/components/InputTag.tsx
  src/pages/diary/create/components/Rating.tsx
  src/pages/diary/create/components/ToggleButton.tsx
  src/pages/diary/create/components/UploadImage.tsx
  src/pages/my/MyPage.tsx
Labels: feat ✨

#153 feat: ✨ 위치 검색 페이지 UI(PP-128)
  src/apis/search.ts
  src/components/InfoItem.tsx
  src/constants/queryKey.ts
  src/features/hooks/queries/useLocationSearch.ts
  src/features/hooks/useSearch.ts
  src/pages/diary/map/search/MapSearchPage.tsx
  src/pages/diary/map/search/components/LocationList.tsx
  src/pages/diary/map/search/components/LocationSearch.tsx
  src/pages/result/place/PlaceListPage.tsx
  src/store/diarySlice.ts
Labels: feat ✨, style 💄

#155 feat: ⚡️ 공간일기작성 위치 검색 API 연동(PP-250)
  src/components/InfoItem.tsx
  src/features/hooks/queries/useCreateDiary.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/map/components/MapNavbar.tsx
  src/utils/Router.tsx
  src/utils/routes.ts
Labels: feat ✨

#157 fix: 🐛 회원정보 추가사항(PP-234)
  src/components/@common/Menu.tsx
  src/features/hooks/useMyForm.ts
  src/features/queries/useAuthResetPw.ts
  src/features/queries/useChangeUserInfo.ts
  src/features/queries/useCheckEmail.ts
  src/features/queries/useCreateDiary.ts
  src/features/queries/useCurrentPw.ts
  src/features/queries/useDeleteDiary.ts
  src/features/queries/useDiaryDetail.ts
  src/features/queries/useDiaryList.ts
  src/features/queries/useEmailResetPw.ts
  src/features/queries/useFindPw.ts
  src/features/queries/useJoin.ts
  src/features/queries/useLocationSearch.ts
  src/features/queries/useLogin.ts
  src/features/queries/usePlaceSearch.ts
  src/features/queries/useReissueToken.ts
  src/features/queries/useResetPw.ts
  src/features/queries/useSearchDetail.ts
  src/features/queries/useUserInfo.ts
  src/features/queries/useWithdraw.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/detail/DiaryDetailPage.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/pages/diary/map/search/components/LocationList.tsx
  src/pages/find/pw/FindPwPage.tsx
  src/pages/join/JoinPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/components/SNSLogin.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/password/MyPwPage.tsx
  src/pages/my/password/UpdateMyPwPage.tsx
  src/pages/my/withdrawal/WithdrawalPage.tsx
  src/pages/reset/ResetPwPage.tsx
  src/pages/result/detail/SearchDetailPage.tsx
  src/pages/result/place/PlaceListPage.tsx
  src/utils/ProtectRouter.tsx
Labels: fix 🐛

#159 docs: 📚 IA(PP-242)
  README.md
  public/images/readme-ia.png
Labels: docs 📚

#161 docs: 📚 Tech Stacks(PP-244)
  README.md
  public/images/readme-tech_stacks.png
Labels: docs 📚

#163 docs: 📚 서비스 개요 작성(PP-240)
  README.md
  public/images/readme-service_outline.png
Labels: docs 📚

#165 docs: 📚 readme 업데이트(PP-247)
  README.md
  public/images/readme-designer.jpeg
  public/images/readme-ia.png
  public/images/readme-ia.svg
  public/images/readme-information_architecture.svg
  public/images/readme-project_goal.svg
  public/images/readme-service_outline.png
  public/images/readme-service_outline.svg
  public/images/readme-tech_stacks.png
  public/images/readme-tech_stacks.svg
  public/images/readme-wansun.jpeg
Labels: docs 📚

#167 feat: ✨ 공간일기 작성 API(PP-252)
  src/features/queries/useCreateDiary.ts
  src/pages/diary/create/DiaryCreatePage.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/styles/DiaryListPage.styles.ts
Labels: feat ✨

#168 feat: ✨ 공간일기 작성 API(PP-252)
  src/pages/diary/detail/DiaryDetailPage.tsx
  src/pages/diary/list/DiaryListPage.tsx
  src/styles/DiaryListPage.styles.ts
Labels: fix 🐛, feat ✨
